version: '3'
services:
  vote:
    build: ./vote
    # use python rather than gunicorn for local dev
    command: python app.py
    depends_on:
      - redis
    volumes:
     - ./vote:/app
    ports:
      - "5000:80"
    networks:
      - front-tier
      - back-tier

  result:
    build: ./result
    # use nodemon rather than node for local dev
    command: nodemon server.js
    depends_on:
      - db
    volumes:
      - ./result:/app
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-tier
      - back-tier

  worker:
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - back-tier

  redis:
    image: redis:5.0-alpine3.10
    ports: ["6379"]
    networks:
      - back-tier
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier
volumes:
  db-data:

networks:
  front-tier:
  back-tier:
# use nodemon rather than node for local dev iss53sd
  # use nodemon rather than node for local dev
  # use nodemon rather than node for local dev
  # use nodemon rather than node for local dev
  # use nodemon rather than node for local dev
  # use nodemon rather than node for local dev
  # use nodemon rather than node for local dev iss53sd
